name: Prettier PR checker

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: --check .
